const actionTypes = {
    APPEND_POKE: "APPEND_POKE",
    APPEND_POKE_DETAIL: "APPEND_POKE_DETAIL",
    REMOVE_POKE_DETAIL: "REMOVE_POKE_DETAIL",
    APPEND_POKE_BY_TYPE: 'APPEND_POKE_BY_TYPE',
    REFINE_POKE_BY_TYPE: 'REFINE_POKE_BY_TYPE',
    REMOVE_POKE_BY_TYPE: 'REMOVE_POKE_BY_TYPE',
    SEARCH_NAME_QUERY: "SEARCH_NAME_QUERY"
};

export default actionTypes;